<a href="https://colab.research.google.com/github/sakshi1998/Hindi-to-english-translator/blob/master/Final_sahi_wala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [0]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [0]:
!pip install -U gensim

Requirement already up-to-date: gensim in /usr/local/lib/python3.6/dist-packages (3.6.0)


In [0]:
file = open('drive/My Drive/inputengsentences(1).txt', 'r')

In [0]:
file = file.read()

In [0]:
file

"Fresh breath and shining teeth enhance your  personality.\t\t\t\t\t\t\t\t\t\t\t\t\t\tYour self-confidence also increases with teeth.\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\nBacteria stay between  our gums and teeth.\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\nThey make  teeth dirty and breath stinky.\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\nYou may keep your teeth clean and breath fresh by the help of some easy tips  given here.\t\t\t\t\t\t\t\t\t\t\tClean your teeth properly.\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\nIt takes two to three minutes to clean your teeth properly.\nBut most of the people give less than one minute for this.\t\t\t\t\t\t\t\t\t\t\t\t\t\tDrink plenty of water.\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\nBacterial attack fast if the mouth dries up .\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tWith this stink come from breath.\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tBy drinking plenty of water not only the left-over pieces of food gets cleaned but saliva also gets formed.\t\t\t\t\t\t\t\t\t\tSaliva has important role in keeping the mout

In [0]:
  
# importing all necessary modules 
from nltk.tokenize import sent_tokenize, word_tokenize 
import warnings 
  
warnings.filterwarnings(action = 'ignore') 
  
import gensim 
from gensim.models import Word2Vec 

In [0]:
s = file

In [0]:
# Replaces escape character with space 
f = s.replace("\n", " ")

In [0]:
#stop words removal
import nltk
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))

In [0]:
data = [] 

In [0]:
# iterate through each sentence in the file 
eng_ind_to_char = {}
k=0

for i in sent_tokenize(f): 
    temp = [] 
    # tokenize the sentence into words 
    for j in word_tokenize(i): 
          temp.append(j.lower())
          eng_ind_to_char[k] = j.lower()
          k=k+1
  
    data.append(temp)

In [0]:
eng_ind_to_char

{0: 'fresh',
 1: 'breath',
 2: 'and',
 3: 'shining',
 4: 'teeth',
 5: 'enhance',
 6: 'your',
 7: 'personality',
 8: '.',
 9: 'your',
 10: 'self-confidence',
 11: 'also',
 12: 'increases',
 13: 'with',
 14: 'teeth',
 15: '.',
 16: 'bacteria',
 17: 'stay',
 18: 'between',
 19: 'our',
 20: 'gums',
 21: 'and',
 22: 'teeth',
 23: '.',
 24: 'they',
 25: 'make',
 26: 'teeth',
 27: 'dirty',
 28: 'and',
 29: 'breath',
 30: 'stinky',
 31: '.',
 32: 'you',
 33: 'may',
 34: 'keep',
 35: 'your',
 36: 'teeth',
 37: 'clean',
 38: 'and',
 39: 'breath',
 40: 'fresh',
 41: 'by',
 42: 'the',
 43: 'help',
 44: 'of',
 45: 'some',
 46: 'easy',
 47: 'tips',
 48: 'given',
 49: 'here',
 50: '.',
 51: 'clean',
 52: 'your',
 53: 'teeth',
 54: 'properly',
 55: '.',
 56: 'it',
 57: 'takes',
 58: 'two',
 59: 'to',
 60: 'three',
 61: 'minutes',
 62: 'to',
 63: 'clean',
 64: 'your',
 65: 'teeth',
 66: 'properly',
 67: '.',
 68: 'but',
 69: 'most',
 70: 'of',
 71: 'the',
 72: 'people',
 73: 'give',
 74: 'less',
 75: '

In [0]:
model = gensim.models.Word2Vec(data, min_count = 1, size = 100, 
                                             window = 5, sg = 1) 

In [0]:
output_of_words=[]
max_x=0
for i in data:
    print(i)
    print("hgg")
    output_of_words.append(model[i])
    max_x=max(max_x,len(model[i]))

['fresh', 'breath', 'and', 'shining', 'teeth', 'enhance', 'your', 'personality', '.']
hgg
['your', 'self-confidence', 'also', 'increases', 'with', 'teeth', '.']
hgg
['bacteria', 'stay', 'between', 'our', 'gums', 'and', 'teeth', '.']
hgg
['they', 'make', 'teeth', 'dirty', 'and', 'breath', 'stinky', '.']
hgg
['you', 'may', 'keep', 'your', 'teeth', 'clean', 'and', 'breath', 'fresh', 'by', 'the', 'help', 'of', 'some', 'easy', 'tips', 'given', 'here', '.']
hgg
['clean', 'your', 'teeth', 'properly', '.']
hgg
['it', 'takes', 'two', 'to', 'three', 'minutes', 'to', 'clean', 'your', 'teeth', 'properly', '.']
hgg
['but', 'most', 'of', 'the', 'people', 'give', 'less', 'than', 'one', 'minute', 'for', 'this', '.']
hgg
['drink', 'plenty', 'of', 'water', '.']
hgg
['bacterial', 'attack', 'fast', 'if', 'the', 'mouth', 'dries', 'up', '.']
hgg
['with', 'this', 'stink', 'come', 'from', 'breath', '.']
hgg
['by', 'drinking', 'plenty', 'of', 'water', 'not', 'only', 'the', 'left-over', 'pieces', 'of', 'food', 

In [0]:
output_of_words

[array([[ 4.6248906e-04, -5.8097427e-04,  6.0113613e-04, ...,
          4.0804766e-04,  9.2857314e-04, -8.7140512e-04],
        [ 4.6485718e-04, -3.5404490e-04,  3.6876736e-04, ...,
         -1.1776326e-04,  5.8125285e-04, -3.3537723e-04],
        [-8.4289326e-04,  9.2765497e-04,  4.4944632e-04, ...,
         -2.5056314e-04, -8.1547286e-04,  2.6179536e-04],
        ...,
        [-8.9072091e-05, -3.7098289e-04, -2.0379313e-04, ...,
         -4.4315009e-04,  4.1728592e-05, -7.9158269e-04],
        [ 9.2911627e-04,  9.2912471e-04,  8.2068588e-04, ...,
         -3.0258932e-04, -2.3318302e-04, -8.3076862e-05],
        [-5.4617267e-04,  6.9505803e-04,  1.0164361e-03, ...,
         -6.2932580e-05, -2.9113228e-04, -1.9767888e-04]], dtype=float32),
 array([[-8.9072091e-05, -3.7098289e-04, -2.0379313e-04, ...,
         -4.4315009e-04,  4.1728592e-05, -7.9158269e-04],
        [ 8.1963645e-04,  9.4930560e-04, -4.4592744e-04, ...,
          2.4048612e-04, -1.2426483e-04,  3.8063421e-04],
        [-

In [0]:
for i in range(len(output_of_words)):
  print(len(output_of_words[i]))

9
7
8
8
19
5
12
13
5
9
7
20
10
10
6
9
9
12
11
6
9
9
6
11
10
11
16
9
8
9
8
17
23
5
14
9
15
15
20
3
12
7
3
9
19
6
17
8
11


In [0]:
with open("drive/My Drive/hindi sentences.txt", encoding='utf-16') as f1:
    s1 = f1.read()
  
# Replaces escape character with space 
f1= s1.replace('|', '')


In [0]:
data1 = [] 
max_y=0

k=0

hin_ind_to_char = {}

# iterate through each sentence in the file 
for i in sent_tokenize(f1): 
    temp = [] 
    # tokenize the sentence into words
    
    for j in word_tokenize(i): 
        if j not in stop_words:
       
          
          if j=="।":
            data1.append(temp)
            temp=[]
          else:
            temp.append(j.lower())
            hin_ind_to_char[k] = j.lower()
            k=k+1

In [0]:
print(data1)

[['ताजा', 'साँसें', 'और', 'चमचमाते', 'दाँत', 'आपके', 'व्यक्तित्व', 'को', 'निखारते', 'हैं'], ['दाँतों', 'से', 'आपका', 'आत्मविश्\u200dवास', 'भी', 'बढ़ता', 'है'], ['हमारे', 'मसूढ़ों', 'और', 'दाँतों', 'के', 'बीच', 'बैक्टीरिया', 'मौजूद', 'होते', 'हैं'], ['ये', 'दाँतों', 'को', 'गंदा', 'और', 'साँसों', 'को', 'बदबूदार', 'बना', 'देते', 'हैं'], ['यहाँ', 'दिए', 'कुछ', 'आसान', 'नुस्खों', 'की', 'मदद', 'से', 'आप', 'अपने', 'दाँतों', 'को', 'स्वच्छ', 'और', 'साँसों', 'को', 'ताजा', 'रख', 'सकते', 'हैं'], ['दाँतों', 'को', 'ठीक', 'से', 'साफ', 'करें'], ['दाँतों', 'को', 'ठीक', 'से', 'साफ', 'करने', 'में', 'दो', 'से', 'तीन', 'मिनट', 'का', 'समय', 'लगता', 'है'], ['लेकिन', 'ज्यादातर', 'लोग', 'इसके', 'लिए', 'एक', 'मिनट', 'से', 'भी', 'कम', 'समय', 'देते', 'हैं'], ['खूब', 'पानी', 'पीएँ'], ['मुँह', 'सूखने', 'पर', 'बैक्टीरिया', 'हमला', 'तेज', 'कर', 'देते', 'हैं'], ['इससे', 'साँसों', 'से', 'बदबू', 'आने', 'लगती', 'है'], ['खूब', 'पानी', 'पीने', 'से', 'न', 'केवल', 'खाने', 'के', 'बचे', '-', 'खुचे', 'टुकड़े', 'साफ', 'हो', 'जात

In [0]:

print( hin_ind_to_char)

    


{0: 'ताजा', 1: 'साँसें', 2: 'और', 3: 'चमचमाते', 4: 'दाँत', 5: 'आपके', 6: 'व्यक्तित्व', 7: 'को', 8: 'निखारते', 9: 'हैं', 10: 'दाँतों', 11: 'से', 12: 'आपका', 13: 'आत्मविश्\u200dवास', 14: 'भी', 15: 'बढ़ता', 16: 'है', 17: 'हमारे', 18: 'मसूढ़ों', 19: 'और', 20: 'दाँतों', 21: 'के', 22: 'बीच', 23: 'बैक्टीरिया', 24: 'मौजूद', 25: 'होते', 26: 'हैं', 27: 'ये', 28: 'दाँतों', 29: 'को', 30: 'गंदा', 31: 'और', 32: 'साँसों', 33: 'को', 34: 'बदबूदार', 35: 'बना', 36: 'देते', 37: 'हैं', 38: 'यहाँ', 39: 'दिए', 40: 'कुछ', 41: 'आसान', 42: 'नुस्खों', 43: 'की', 44: 'मदद', 45: 'से', 46: 'आप', 47: 'अपने', 48: 'दाँतों', 49: 'को', 50: 'स्वच्छ', 51: 'और', 52: 'साँसों', 53: 'को', 54: 'ताजा', 55: 'रख', 56: 'सकते', 57: 'हैं', 58: 'दाँतों', 59: 'को', 60: 'ठीक', 61: 'से', 62: 'साफ', 63: 'करें', 64: 'दाँतों', 65: 'को', 66: 'ठीक', 67: 'से', 68: 'साफ', 69: 'करने', 70: 'में', 71: 'दो', 72: 'से', 73: 'तीन', 74: 'मिनट', 75: 'का', 76: 'समय', 77: 'लगता', 78: 'है', 79: 'लेकिन', 80: 'ज्यादातर', 81: 'लोग', 82: 'इसके', 83: 'लिए', 84:

In [0]:
model = gensim.models.Word2Vec(data1, min_count = 1, size = 100, 
                                             window = 5, sg = 1) 


In [0]:
input_of_words=[]

sum1=0;


for i in data1:
  input_of_words.append(model[i])
  max_y=max(max_y,len(model[i]))
  

In [0]:
print(max_x)
print(max_y)

23
30


In [0]:
from keras.preprocessing import sequence
from keras.models import Model
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM,Input
from keras.layers import Lambda
import numpy as np
from keras.layers import TimeDistributed
regressor=Sequential()

In [0]:
input_of_words=np.array(input_of_words)
output_of_words=np.array(output_of_words)

In [0]:
def change(sent,new_val,max_l,r):
  
  z=np.zeros([1,100])
  cc=49
  k=0
  
  for i in sent:
 
    if cc>0:
      count=max_l-i.shape[0]
      
      while count>0:
      
        i=np.concatenate((i, z)) 
      
        count=count-1
      
      
      new_val[k]=i
      k=k+1
    
    
      cc=cc-1
  
    else:
      break
  return new_val

In [0]:

#padding the values

new_input=np.zeros([49,30,100])
new_input=change(input_of_words,new_input,max_y,513)
new_output=np.zeros([49,23,100])
new_output=change(output_of_words,new_output,max_x,524)


ValueError: ignored

In [0]:
print(new_input.shape)
new_output.shape

(49, 30, 100)


(49, 23, 100)

In [0]:
regressor.add(LSTM(units=100,activation='sigmoid',return_sequences=True,input_shape=(30,100)))

regressor.add(Lambda(lambda x: x[:, -23:, :]))
                     
regressor.compile(optimizer='adam',loss='binary_crossentropy', metrics = ['accuracy'])
regressor.add(Dropout(0.2))
regressor.fit(new_input,new_output,batch_size=1,epochs=12)


Epoch 1/12
49/49 [==============================] - 5s 98ms/step - loss: 0.2876 - acc: 0.5439
Epoch 2/12
49/49 [==============================] - 4s 74ms/step - loss: 0.1936 - acc: 0.5439
Epoch 3/12
49/49 [==============================] - 4s 74ms/step - loss: 0.1591 - acc: 0.5439
Epoch 4/12
49/49 [==============================] - 4s 74ms/step - loss: 0.1473 - acc: 0.5439
Epoch 5/12
49/49 [==============================] - 4s 75ms/step - loss: 0.1418 - acc: 0.5439
Epoch 6/12
49/49 [==============================] - 4s 74ms/step - loss: 0.1360 - acc: 0.5439
Epoch 7/12
49/49 [==============================] - 4s 74ms/step - loss: 0.1291 - acc: 0.5439
Epoch 8/12
49/49 [==============================] - 4s 74ms/step - loss: 0.1213 - acc: 0.5439
Epoch 9/12
49/49 [==============================] - 4s 73ms/step - loss: 0.1129 - acc: 0.5439
Epoch 10/12
49/49 [==============================] - 4s 73ms/step - loss: 0.1039 - acc: 0.5439
Epoch 11/12
49/49 [==============================] - 4s 74m

In [0]:
#testing LSTM Model

preds=regressor.predict(new_inwo)
print(preds)


for i in range(0,len(new_inwo)):
    sampled_token_index=np.argmax(preds[0][i])
    print(sampled_token_index) 

print(eng_ind_to_char[sampled_token_index])

[[[0.         0.11861545 0.01986224 ... 0.         0.1491334  0.07991961]
  [0.02970751 0.13553502 0.07699816 ... 0.06047178 0.15412298 0.10287002]
  [0.         0.12122726 0.03356201 ... 0.00878258 0.14928876 0.08411054]
  ...
  [0.         0.12740909 0.05540852 ... 0.03472586 0.15074748 0.09191865]
  [0.         0.12762056 0.05604584 ... 0.03544764 0.15082482 0.09217865]
  [0.         0.12744991 0.05553132 ... 0.03486605 0.15076356 0.09196711]]]
10
self-confidence


In [0]:
#   ----------sequence to sequence------------ 



In [0]:
### sequence to sequence

#ENCODER MODEL
'''
encoder_input=Input(shape=(30,100))

encoder=LSTM(100,return_state=True)

encoder_outputs,encoder_h,encoder_c= encoder(encoder_input)



encoder_states=[encoder_h,encoder_c]
'''

In [0]:
encoder_input

<tf.Tensor 'input_5:0' shape=(?, 30, 100) dtype=float32>

In [0]:
print(encoder_h)

Tensor("lstm_5/while/Exit_3:0", shape=(?, 100), dtype=float32)


In [0]:
encoder_c

<tf.Tensor 'lstm_5/while/Exit_4:0' shape=(?, 100) dtype=float32>

In [0]:
encoder_outputs


<tf.Tensor 'lstm_5/TensorArrayReadV3:0' shape=(?, 100) dtype=float32>

In [0]:
#Decoder Model

decoder_input=Input(shape=(None,100))
decoder_LSTM=LSTM(100,return_sequences=True,return_state=True)
decoder_out, _ , _ = decoder_LSTM(decoder_input, initial_state=encoder_states)
decoder_dense = Dense(100,activation='softmax')
decoder_out = decoder_dense (decoder_out)



In [0]:

decoder_out



<tf.Tensor 'dense_2/truediv:0' shape=(?, ?, 100) dtype=float32>

In [0]:
decoder_input

<tf.Tensor 'input_6:0' shape=(?, ?, 100) dtype=float32>

In [0]:
model = Model(inputs=[encoder_input, decoder_input],outputs=[decoder_out])

# Run training
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics = ['accuracy'])
model.fit(x=[new_input, new_output], 
          y=new_output,
          batch_size=1,
          epochs=15)

Epoch 1/15
49/49 [==============================] - 7s 149ms/step - loss: -0.0480 - acc: 0.0364
Epoch 2/15
49/49 [==============================] - 6s 122ms/step - loss: -0.1090 - acc: 0.0435
Epoch 3/15
49/49 [==============================] - 6s 123ms/step - loss: -0.1229 - acc: 0.0399
Epoch 4/15
49/49 [==============================] - 6s 122ms/step - loss: -0.1272 - acc: 0.0382
Epoch 5/15
49/49 [==============================] - 6s 123ms/step - loss: -0.1288 - acc: 0.0399
Epoch 6/15
49/49 [==============================] - 6s 123ms/step - loss: -0.1299 - acc: 0.0337
Epoch 7/15
49/49 [==============================] - 6s 123ms/step - loss: -0.1303 - acc: 0.0408
Epoch 8/15
49/49 [==============================] - 6s 122ms/step - loss: -0.1309 - acc: 0.0337
Epoch 9/15
49/49 [==============================] - 6s 122ms/step - loss: -0.1312 - acc: 0.0373
Epoch 10/15
49/49 [==============================] - 6s 122ms/step - loss: -0.1317 - acc: 0.0293
Epoch 11/15
49/49 [====================

In [0]:
#testing encoder-decoder

encoder_model_inf = Model(encoder_input, encoder_states)

encoder_model_inf.summary()

# Decoder inference model
decoder_state_input_h = Input(shape=(100,))

decoder_state_input_c = Input(shape=(100,))


decoder_input_states = [decoder_state_input_h, decoder_state_input_c]


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         (None, 30, 100)           0         
_________________________________________________________________
lstm_5 (LSTM)                [(None, 100), (None, 100) 80400     
Total params: 80,400
Trainable params: 80,400
Non-trainable params: 0
_________________________________________________________________


In [0]:
decoder_input_states

[<tf.Tensor 'input_7:0' shape=(?, 100) dtype=float32>,
 <tf.Tensor 'input_8:0' shape=(?, 100) dtype=float32>]

In [0]:



decoder_out, decoder_h, decoder_c = decoder_LSTM(decoder_input, 
                                                 initial_state=decoder_input_states)
decoder_states = [decoder_h , decoder_c]

print(decoder_states)

[<tf.Tensor 'lstm_6_1/while/Exit_2:0' shape=(?, 100) dtype=float32>, <tf.Tensor 'lstm_6_1/while/Exit_3:0' shape=(?, 100) dtype=float32>]


In [0]:
decoder_out = decoder_dense(decoder_out)
decoder_out


<tf.Tensor 'dense_2_1/truediv:0' shape=(?, ?, 100) dtype=float32>

In [0]:
decoder_model_inf = Model(inputs=[decoder_input] + decoder_input_states,
                          outputs=[decoder_out] + decoder_states )

encoder_model_inf.summary()-

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         (None, 30, 100)           0         
_________________________________________________________________
lstm_5 (LSTM)                [(None, 100), (None, 100) 80400     
Total params: 80,400
Trainable params: 80,400
Non-trainable params: 0
_________________________________________________________________


In [0]:
def decode_seq(inp_seq,x):
    
    # Initial states value is coming from the encoder 
    states_val = encoder_model_inf.predict(inp_seq)
    
    
    
    target_seq = np.zeros((1,1,100))
   
    translated_sent = ''
   
   
    stop_condition = False
    
    
    while not stop_condition:
        
        decoder_out, decoder_h, decoder_c = decoder_model_inf.predict(x=[target_seq]+ states_val)
        
        max_val_index = np.argmax(decoder_out[0,-1,:])
       
      
        sampled_fra_word = eng_ind_to_char[max_val_index]
        
        
        translated_sent += sampled_fra_word+' '
        
        if ( (sampled_fra_word == '\n') or (len(translated_sent) > max_x)) :
            stop_condition = True
       
      
        target_seq = np.zeros((1, 1,100))
        
        target_seq[0, 0 ,max_val_index]=1
        
        states_val = [decoder_h, decoder_c]
        
    return translated_sent
   

In [0]:
input_test='ताजा साँसें और चमचमाते दाँत आपके व्यक्तित्व को निखारते हैं'

temp=[]
data3=[]
for i in word_tokenize(input_test): 
    temp.append(i)
len1=len(temp)    
data3.append(temp)

model3=Word2Vec(data3, min_count = 1, size = 100)
 
in_wo=[]

for i in data3:
  in_wo.append(model3[i])
  




In [0]:

#padding of input_sentence

x=len(in_wo[0])


in_wo=np.array(in_wo)


new_inwo=np.zeros([1,30,100])

new_inwo=change(in_wo,new_inwo,max_y)



In [0]:
translated_sent = decode_seq(new_inwo,len(new_inwo))

translated_sent


'. . . given given given '